services:

  api:
    build: .
    container_name: atividade_api
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      DB_HOST: mysql
      MONGO_URI: mongodb://mongo:27017/atividade
    depends_on:
      mysql:
        condition: service_healthy
      mongo:
        condition: service_started
    restart: on-failure

  mysql:
    image: mysql:8.0
    container_name: atividade_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: atividade
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10

  mongo:
    image: mongo:7
    container_name: atividade_mongo
    volumes:
      - mongo_data:/data/db

volumes:
  mysql_data:
  mongo_data:
